Repository the-virtual-brain/tvb-widgets, pull requests merged in 2023-01, with the labels that each got.

#27 WID-107: noise applied differently for each SV
  tvbwidgets/ui/phase_plane_widget.py
Labels: enhancement

#29 WID-63: TSWidget compatible with MNE > 1.0
  setup.py
  tvbwidgets/tests/test_ts_widget.py
  tvbwidgets/ui/ts_widget.py
  tvbwidgets/ui/ts_widget_help.ini
Labels: enhancement

#31 WID-73: show info when surfaces with incompatible coloring are combined
  tvbwidgets/ui/head_widget.py
Labels: bug, enhancement

#32 prepare for release 1.1
  .github/workflows/build.yml
  dev/Dockerfile
  dev/prepare_env.sh
  tvbwidgets/ui/head_widget.py
Labels: documentation, enhancement
