Repository the-virtual-brain/tvb-widgets, pull requests merged in 2023-04, with the labels that each got.

#43 WID-176: add a function that plots a timeseries to the api
  tvbwidgets/api.py
Labels: documentation, enhancement

#44 WID-191: fix prepare_env.bat file
  dev/prepare_env.bat
Labels: bug

#45 Upgrade Plotly version
  package.json
  requirements.txt
Labels: enhancement

#41 WID-78: PSE widget local launch
  .github/workflows/build.yml
  notebooks/PSELauncher.ipynb
  notebooks/PSEWidget.ipynb
  requirements.txt
  setup.py
  tvbwidgets/api.py
  tvbwidgets/core/pse/__init__.py
  tvbwidgets/core/pse/parameters.py
  tvbwidgets/core/pse/pse_data.py
  tvbwidgets/ui/pse_launcher_widget.py
  tvbwidgets/ui/pse_widget.py
Labels: enhancement

#49 WID-211: move the notebooks running action to a different yml file
  .github/workflows/build.yml
  .github/workflows/notebooks.yml
  dev/notebook_runner.py
Labels: bug

#46 WID-79: HPC launch
  notebooks/PSELauncher.ipynb
  package.json
  requirements.txt
  tvbwidgets/api.py
  tvbwidgets/core/hpc/config.py
  tvbwidgets/core/hpc/launcher.py
  tvbwidgets/core/pse/parameters.py
  tvbwidgets/ui/pse_launcher_widget.py
  tvbwidgets/ui/pse_widget.py
Labels: enhancement
