Repository the-virtual-brain/tvb-widgets, pull requests merged in 2024-07, with the labels that each got.

#74 WID-247 - SpaceTimeVisualizer widget
  notebooks/ConnectivitySpaceTimeWidget.ipynb
  tvbwidgets/api.py
  tvbwidgets/tests/test_spacetime_widget.py
  tvbwidgets/ui/spacetime_widget.py
Labels: enhancement, good first issue

#78 EBR-85: fix Sonar issues, set size to plots overview tab
  tvbwidgets/tests/test_spacetime_widget.py
  tvbwidgets/ui/dicom_widget.py
  tvbwidgets/ui/spacetime_widget.py
Labels: bug

#77 EBR-79: add access to bucket from widgets
  notebooks/HeadWidget.ipynb
  requirements.txt
  tvbwidgets/core/bucket/bucket_api.py
  tvbwidgets/core/bucket/buckets.py
  tvbwidgets/core/exceptions.py
  tvbwidgets/core/hpc/config.py
  tvbwidgets/tests/test_bucket_widget.py
  tvbwidgets/tests/test_drive_widget.py
  tvbwidgets/tests/test_head_widget.py
  tvbwidgets/ui/bucket_widget.py
  tvbwidgets/ui/storage_widget.py
  tvbwidgets/ui/ts/ts_widget_browser.py
  tvbwidgets/ui/widget_with_browser.py
Labels: enhancement
